service: lswn-aws-node-express-dynamode-api
frameworkVersion: '3'

custom:
  tableName: 'LSWN-TABLE-${sls:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            # UserTableからArn呼び出し
  environment:
    TABLE_NAME: tableName # 4番ライン参照

functions:
  create: # API名
    handler: handler/createHandler.createHandler
    events:
      - http: # httpApi (x), http (o)
          path: dynamo
          method: post
          cors: true
  list: # API名
    handler: handler/listHandler.listHandler
    events:
      - http: # httpApi (x), http (o)
          path: dynamo/list
          method: get
          cors: true
  get: # API名
    handler: handler/getHandler.getHandler
    events:
      - http: # httpApi (x), http (o)
          path: dynamo/{id} # parameter input
          method: get
          cors: true
  delete: # API名
    handler: handler/deleteHandler.deleteHandler
    events:
      - http: # httpApi (x), http (o)
          path: dynamo/{id} # parameter input
          method: delete
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: tableName